services:
  postgres:
    image: postgres:16
    container_name: controle-apostas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controle_apostas
    ports:
      - "5432:5432"
    volumes:
      - controle-apostas-data:/var/lib/postgresql/data

volumes:
  controle-apostas-data:
